resources:
  repositories:
    - repository: templates
      type: github
      name: rdbartram/PSBuildRelease
      ref: refs/heads/master
      endpoint: rdbartram

jobs:
  - template: Yaml Build Defintions/ModuleTestIncPublish.yml@templates
    parameters:
      baseRepoId: rdbartram/PSTerraformParser
      baseBuildDefinitionId: 8
      coverageThreshold: 0
      moduleName: PSTerraformParser
      agent: Hosted VS2017
